name: Node.js CI

on:
  push:
      branches: ["main"]
  pull_request: 
        branches: ["main", "dev"]

jobs:
    build:
        name: Backend test
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./quirknotes/backend

        strategy:
            matrix:
                node-version: [20.x]
                mongodb-version: ['6.0']

        steps:
            - uses: actions/checkout@v3

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                mongodb-version: ${{ matrix.mongodb-version }}
                mongodb-port: 27017

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm i
            - run: npm start &
            - run: npm test
